import { kioskScale } from '@shared/utils/kioskLayout';

/** Compact layout tokens for retail scan cart (more lines visible on screen). */
export const retailScanLayout = {
  horizontalPadding: kioskScale(48),

  scannerZonePaddingTop: kioskScale(12),
  scannerZonePaddingBottom: kioskScale(16),

  cartPanelPaddingH: kioskScale(48),
  cartPanelPaddingTop: kioskScale(20),
  cartPanelContentPaddingBottom: kioskScale(16),
  sectionHeaderPaddingBottom: kioskScale(16),
  sectionDividerWidth: kioskScale(2.88),

  headerPaddingBottom: kioskScale(12),
  headerChipFontSize: kioskScale(26),
  headerChipPaddingH: kioskScale(18),
  headerChipPaddingV: kioskScale(8),
  headerDotSize: kioskScale(10),

  promptPaddingH: kioskScale(24),
  promptPaddingV: kioskScale(20),
  promptContentGap: kioskScale(12),
  promptHeaderGap: kioskScale(12),
  promptGap: kioskScale(12),
  promptMarginBottom: kioskScale(12),
  promptRadius: kioskScale(28),
  promptBorderWidth: kioskScale(2),
  promptLabelSize: kioskScale(26),
  promptLabelLineHeight: kioskScale(32),
  promptHeadlineSize: kioskScale(34),
  promptHeadlineLineHeight: kioskScale(42),
  promptTitleSize: kioskScale(30),
  promptTitleLineHeight: kioskScale(36),
  promptLineSize: kioskScale(24),
  promptLineLineHeight: kioskScale(30),
  promptIconCircleSize: kioskScale(56),
  /** Figma scan barcode icon (35×35) scaled for kiosk. */
  promptIconSize: kioskScale(32),

  sectionTitleSize: kioskScale(38),
  sectionTitleLineHeight: kioskScale(44),
  sectionCartIconSize: kioskScale(36),
  sectionBadgeSize: kioskScale(36),
  sectionBadgeFontSize: kioskScale(22),
  sectionClearSize: kioskScale(26),
  sectionClearIconSize: kioskScale(24),
  sectionPaddingBottom: kioskScale(10),

  lineListGap: kioskScale(14),
  lineListPaddingTop: kioskScale(16),
  lineItemRadius: kioskScale(28),
  lineItemBorderWidth: kioskScale(2),
  lineCardPadding: kioskScale(20),
  lineItemGap: kioskScale(12),
  lineImageBoxSize: kioskScale(96),
  lineImageBoxRadius: kioskScale(16),
  lineImageInnerSize: kioskScale(72),
  lineContentPaddingLeft: kioskScale(4),
  lineTextGap: kioskScale(4),
  lineNameSize: kioskScale(30),
  lineNameLineHeight: kioskScale(36),
  lineModifiersSize: kioskScale(22),
  linePriceSize: kioskScale(28),
  linePriceLineHeight: kioskScale(34),
  lineSecondaryPriceSize: kioskScale(24),
  lineSecondaryPriceLineHeight: kioskScale(30),
  lineActionsGap: kioskScale(12),
  lineRemoveButtonSize: kioskScale(48),
  lineRemoveIconSize: kioskScale(22),
  lineQtyButtonSize: kioskScale(40),
  lineQtyValueSize: kioskScale(28),
  lineQtyValueLineHeight: kioskScale(32),
  lineQtyIconSize: kioskScale(16),
  lineStepperGap: kioskScale(8),
  lineStepperPaddingH: kioskScale(8),
  lineStepperPaddingV: kioskScale(4),

  footerPaddingH: kioskScale(48),
  footerPaddingTop: kioskScale(20),
  footerPaddingBottom: kioskScale(28),
  footerGap: kioskScale(16),
  footerRadius: 0,
  footerBorderWidth: 0,
  footerScrollBottomInset: kioskScale(300),

  checkoutSummaryGap: kioskScale(16),
  checkoutSummaryTextGap: kioskScale(4),
  checkoutCartIconBoxSize: kioskScale(56),
  checkoutCartIconBoxRadius: kioskScale(14),
  checkoutCartIconSize: kioskScale(36),
  checkoutItemsSelectedSize: kioskScale(22),
  checkoutItemsSelectedLineHeight: kioskScale(28),
  checkoutOrderTitleSize: kioskScale(32),
  checkoutOrderTitleLineHeight: kioskScale(38),
  checkoutTotalAmountSize: kioskScale(40),
  checkoutTotalAmountLineHeight: kioskScale(48),
  checkoutConversionSize: kioskScale(22),
  checkoutConversionLineHeight: kioskScale(28),
  checkoutRateRowGap: kioskScale(12),
  checkoutRateDotGap: kioskScale(8),
  checkoutRateDotSize: kioskScale(10),
  checkoutRateLabelSize: kioskScale(22),
  checkoutRateLabelLineHeight: kioskScale(28),

  payButtonRadius: kioskScale(28),
  payButtonPaddingVertical: kioskScale(32),
  payButtonPaddingHorizontal: kioskScale(40),
  payButtonGap: kioskScale(16),
  payButtonIconBoxSize: kioskScale(52),
  payButtonIconBoxRadius: kioskScale(14),
  payButtonCardIconWidth: kioskScale(32),
  payButtonCardIconHeight: kioskScale(28),
  payButtonFontSize: kioskScale(32),
  payButtonLineHeight: kioskScale(40),
  payButtonArrowWidth: kioskScale(28),
  payButtonArrowHeight: kioskScale(24),

  /** Legacy compact tokens for shared cart checkout components. */
  checkoutRowGap: kioskScale(8),
  checkoutRowLabelSize: kioskScale(26),
  checkoutRowLabelLineHeight: kioskScale(32),
  checkoutRowValueSize: kioskScale(26),
  checkoutRowValueLineHeight: kioskScale(32),
  checkoutTotalLabelSize: kioskScale(32),
  checkoutTotalLabelLineHeight: kioskScale(40),
  checkoutTotalValueSize: kioskScale(34),
  checkoutTotalValueLineHeight: kioskScale(42),
  checkoutSummaryPaddingBottom: kioskScale(8),
  checkoutDividerHeight: kioskScale(2),
  bcvBannerRadius: kioskScale(24),
  bcvBannerPaddingV: kioskScale(12),
  bcvBannerPaddingH: kioskScale(16),
  bcvLabelSize: kioskScale(24),
  bcvRateSize: kioskScale(28),
  ctaRadius: kioskScale(28),
  ctaPaddingHorizontal: kioskScale(48),
  ctaPaddingVertical: kioskScale(20),
  ctaGap: kioskScale(10),
  ctaFontSize: kioskScale(32),
  ctaLineHeight: kioskScale(40),
  ctaIconWidth: kioskScale(28),
  ctaIconHeight: kioskScale(26),
};
