import { brand } from './brand';
import { kioskScale } from '../utils/kioskLayout';

/**
 * Tokens for cream-background kiosk steps (Figma 1080×1920).
 * Shared across introduction, ordering menu (P4), and related screens.
 */
export const kioskScreenColors = {
  screenBackground: '#fff7ef',
  title: brand.navy,
  subtitle: '#64748b',
  cardBackground: brand.white,
  cardBorder: 'rgba(7, 20, 58, 0)',
  backButtonBackground: brand.white,
  backButtonBorder: '#f1f5f9',

  /** P4 · Menú — text & surfaces */
  menuSectionMuted: '#6b7280',
  menuSectionHeading: '#1e293b',
  categorySelectedBg: '#ffdcb8',
  categorySelectedBorder: brand.amber,
  searchBackground: '#f8f9fb',
  searchBorderDefault: 'transparent',
  searchBorderFocusOrange: brand.amber,
  searchBorderFocusBlue: brand.blue,
  creamInset: '#fff7ef',
  priceAccent: brand.amber,
  badgeNew: brand.gold,
  badgePopular: brand.amber,
  badgeSoldOut: '#6b7280',
  addButtonMuted: 'rgba(245, 158, 11, 0.1)',
  highlightRing: '#f59e0b',
  cartBar: brand.navy,
  cartBarMutedText: '#d1d5db',
  cartBadge: '#f59e0b',
  cartNextOverlay: 'rgba(255, 255, 255, 0.1)',
  cartIcon: brand.white,

  /** P5 · Detalle producto */
  productDetailHeroBg: '#fff4dd',
  productDetailBorder: '#f3f4f6',
  quantityStepperMinusBg: '#fff7ef',

  /** P6 · Modificadores / toppings */
  modifierSelectedBg: 'rgba(255, 176, 90, 0.1)',
  modifierPriceFree: '#16a34a',
  modifierChipBg: '#fef3c7',
  modifierChipBorder: 'rgba(245, 158, 11, 0.3)',

  /** P7 · Carrito */
  cartAddMoreBorder: '#9ca3af',
  cartLineRemoveIcon: '#9ca3af',

  /** P8 · Checkout sheet sobre carrito */
  cartCheckoutBackdrop: 'rgba(30, 41, 59, 0.35)',
  /** Figma 41:93 */
  cartCheckoutBcvBannerBg: 'rgba(255, 149, 62, 0.1)',
  cartCheckoutBcvBannerBorder: 'rgba(255, 149, 62, 0.2)',
  cartCheckoutBcvLabel: 'rgba(255, 149, 62, 0.8)',
  cartCheckoutBcvRate: '#ff953e',
  cartCheckoutTotalLabel: '#1e293b',
  cartCheckoutTotalValue: '#f59e0b',
  cartCheckoutDivider: '#f3f4f6',

  /** P9 · Método de pago (Figma 43:155) */
  paymentMethodIconBg: '#fffbeb',
  paymentMethodIconBorder: 'rgba(7, 20, 58, 0.1)',
  paymentMethodCardBorder: 'rgba(7, 20, 58, 0.05)',
  paymentMethodSubtitle: 'rgba(7, 20, 58, 0.4)',
  paymentMethodRadioBorder: 'rgba(7, 20, 58, 0.2)',
  paymentMethodRadioSelected: '#f59e0b',

  /** P10 (a) · POS / ECR (Figma 47:2) */
  paymentPosHeroIconBorder: 'rgba(7, 20, 58, 0.1)',

  /** P11–P12.1 · Confirmación referencia */
  paymentReferenceMuted: '#6b7280',
  paymentReferenceInputBorder: '#e6e7eb',
  paymentReferenceKeypadKeyBg: brand.white,
  paymentReferenceKeypadKeyBorder: '#e6e7eb',

  /** P14 / P14.1 · Resultado pedido */
  paymentOutcomeOrderCardBg: '#ffeddd',
  paymentOutcomeOrderCardBorder: '#ffdbbd',
  paymentOutcomeAccent: '#f58220',
  paymentOutcomeQrPaymentStatus: '#ff953e',
} as const;

export const kioskScreenLayout = {
  horizontalPadding: kioskScale(54.857),
  headerPaddingVertical: kioskScale(54.857),
  titleSize: kioskScale(70),
  titleLineHeight: kioskScale(82.286),
  subtitleSize: kioskScale(40),
  subtitleLineHeight: kioskScale(64),
  headerTextGap: kioskScale(20),
  headerBottomSpacing: kioskScale(91.429),
  optionsGap: kioskScale(45.714),
  optionsBottomPadding: kioskScale(182.857),
  cardRadius: kioskScale(54.857),
  cardBorderWidth: kioskScale(4.571),
  cardPaddingVertical: kioskScale(54.857),
  cardPaddingHorizontal: kioskScale(59.428),
  cardInnerGap: kioskScale(54.857),
  cardIconSize: kioskScale(182.857),
  cardLabelSize: kioskScale(54.857),
  cardLabelLineHeight: kioskScale(73.143),
  cardDescriptionSize: kioskScale(36.571),
  cardDescriptionLineHeight: kioskScale(54.857),
  cardDescriptionMarginTop: kioskScale(9.143),
  backButtonSize: kioskScale(109.714),
  backButtonBorderWidth: kioskScale(2.286),
  backIconWidth: kioskScale(36),
  backIconHeight: kioskScale(41.143),

  /** P4 · Menú principal (Figma node 35:2) */
  menuHorizontalPadding: kioskScale(46.08),
  menuHeaderPaddingTop: kioskScale(54.857),
  menuHeaderPaddingBottom: kioskScale(34.56),
  menuSearchHeaderGap: kioskScale(24),
  searchSectionPaddingVertical: kioskScale(34.56),
  searchInputPaddingVertical: kioskScale(34.56),
  searchInputPaddingRight: kioskScale(46.08),
  searchIconSize: kioskScale(46.08),
  searchIconInset: kioskScale(46.08),
  searchFontSize: kioskScale(40.32),
  searchBorderWidth: kioskScale(4),
  categoriesSectionGap: kioskScale(30),
  categoriesTitleSize: kioskScale(40),
  categoriesTitleLineHeight: kioskScale(57.6),
  categoryTabHeight: kioskScale(92),
  categoryTabMinWidth: kioskScale(280),
  categoryTabRadius: kioskScale(32),
  categoryTabBorderWidth: kioskScale(3),
  categoryTabGap: kioskScale(8),
  categoryTabImageHeight: kioskScale(38),
  categoryTabImageWidth: kioskScale(38),
  categoryTabLabelSize: kioskScale(30),
  categoryTabsGap: kioskScale(10),
  menuSectionGap: kioskScale(20),
  menuSectionTitleSize: kioskScale(40),
  menuSectionTitleLineHeight: kioskScale(80.64),
  featuredCardRadius: kioskScale(46.08),
  featuredCardBorderWidth: kioskScale(2.88),
  featuredCardPadding: kioskScale(48.96),
  featuredCardGap: kioskScale(46.08),
  featuredImageSize: kioskScale(276.48),
  featuredImageRadius: kioskScale(34.56),
  featuredTitleSize: kioskScale(45),
  featuredDescriptionSize: kioskScale(35),
  featuredPriceSize: kioskScale(50),
  featuredAddSize: kioskScale(92.16),
  /** Ancho de card en carrusel destacados (1080 − menuHorizontalPadding×2). */
  featuredCarouselCardWidth: kioskScale(987.84),
  featuredCarouselGap: kioskScale(20),
  featuredCarouselPaddingVertical: kioskScale(24),
  featuredAddIconWidth: kioskScale(40.32),
  featuredAddIconHeight: kioskScale(46.08),
  productCardRadius: kioskScale(46.08),
  productCardBorderWidth: kioskScale(2.88),
  productCardPadding: kioskScale(37.44),
  productGridColumnWidth: kioskScale(476.64),
  badgeRibbonRadius: kioskScale(42),
  badgeRibbonTopOffset: kioskScale(3.72),
  productImageHeight: kioskScale(368.64),
  productImageRadius: kioskScale(34.56),
  productImagePadding: kioskScale(23.04),
  productTitleSize: kioskScale(34.56),
  productPriceSize: kioskScale(46.08),
  productAddSize: kioskScale(80.64),
  /** Figma 35:54 — icono + / ✓ dentro del círculo */
  productAddIconWidth: kioskScale(35.28),
  productAddIconHeight: kioskScale(40.32),
  /** Badge de cantidad sobre el botón + (producto en carrito). */
  productAddQtyBadgeMinSize: kioskScale(32),
  productAddQtyBadgeFontSize: kioskScale(20),
  productAddQtyBadgeOffset: kioskScale(-6),
  productGridGap: kioskScale(34.56),
  badgeFontSize: kioskScale(25),
  badgePaddingHorizontal: kioskScale(23.04),
  badgePaddingVertical: kioskScale(11.52),
  cartBarRadius: kioskScale(46.08),
  cartBarPadding: kioskScale(46.08),
  cartBarBottom: kioskScale(62.76),
  cartIconWidth: kioskScale(64.8),
  cartIconHeight: kioskScale(57.6),
  cartChevronWidth: kioskScale(25.2),
  cartChevronHeight: kioskScale(40.32),
  cartCountSize: kioskScale(34.56),
  cartLabelSize: kioskScale(35),
  cartTotalSize: kioskScale(50),
  cartNextSize: kioskScale(45),
  cartNextPaddingHorizontal: kioskScale(46.08),
  cartNextPaddingVertical: kioskScale(23.04),
  menuScrollBottomInset: kioskScale(240),

  /** P5 · Detalle producto (Figma node 35:146) */
  productDetailHeaderHeight: kioskScale(220),
  productDetailContentPadding: kioskScale(69.12),
  productDetailHeroHeight: kioskScale(539),
  /** Espacio interno para que la sombra de la foto no se recorte abajo. */
  productDetailHeroPaddingTop: kioskScale(22),
  productDetailHeroPaddingBottom: kioskScale(44),
  /** Margen bajo el panel para que no se recorten las sombras al scroll. */
  productDetailHeroShadowMargin: kioskScale(20),
  productDetailHeroRadius: kioskScale(115.2),
  productDetailHeroImageWidth: kioskScale(650),
  productDetailHeroImageHeight: kioskScale(477),
  productDetailHeroImageRadius: kioskScale(34.56),
  productDetailTitleSize: kioskScale(70),
  productDetailTitleLineHeight: kioskScale(86.4),
  productDetailPriceSize: kioskScale(70),
  productDetailPriceLineHeight: kioskScale(92.16),
  productDetailDescriptionSize: kioskScale(40),
  productDetailDescriptionLineHeight: kioskScale(65.52),
  productDetailSectionGap: kioskScale(20),
  productDetailQuantityRowHeight: kioskScale(176),
  productDetailQuantityRowRadius: kioskScale(46.08),
  productDetailQuantityRowBorderWidth: kioskScale(2.88),
  productDetailQuantityLabelSize: kioskScale(50),
  productDetailQuantityLabelLineHeight: kioskScale(69.12),
  productDetailStepperPaddingHorizontal: kioskScale(25.92),
  productDetailStepperPaddingVertical: kioskScale(14.4),
  productDetailStepperGap: kioskScale(46.08),
  productDetailStepperButtonSize: kioskScale(92.16),
  productDetailStepperValueSize: kioskScale(50),
  productDetailStepperValueLineHeight: kioskScale(80.64),
  productDetailStepperIconWidth: kioskScale(40.32),
  productDetailStepperIconHeight: kioskScale(46.08),
  productDetailBottomRadius: kioskScale(69.12),
  productDetailBottomPadding: kioskScale(46.08),
  productDetailBottomPaddingTop: kioskScale(48.96),
  productDetailBottomGap: kioskScale(46.08),
  productDetailBottomBorderWidth: kioskScale(2.88),
  productDetailCartIconWidth: kioskScale(45.36),
  productDetailCartIconHeight: kioskScale(40.32),
  productDetailCartLabelSize: kioskScale(40),
  productDetailCartLabelLineHeight: kioskScale(46.08),
  productDetailCartTotalSize: kioskScale(50),
  productDetailCartTotalLineHeight: kioskScale(57.6),
  productDetailCtaRadius: kioskScale(48.571),
  productDetailCtaPaddingVertical: kioskScale(48.571),
  productDetailCtaFontSize: kioskScale(55),
  productDetailCtaLineHeight: kioskScale(85),
  productDetailCtaIconWidth: kioskScale(61.473),
  productDetailCtaIconHeight: kioskScale(54.643),
  productDetailScrollBottomInset: kioskScale(420),

  /** P6 · Modificadores (Figma node 35:202) */
  modifiersHeaderPaddingHorizontal: kioskScale(72.857),
  modifiersHeaderGap: kioskScale(20),
  modifiersTitleSize: kioskScale(70),
  modifiersTitleLineHeight: kioskScale(91.071),
  modifiersSubtitleSize: kioskScale(42.5),
  modifiersSubtitleLineHeight: kioskScale(69.063),
  modifiersGridPaddingHorizontal: kioskScale(72.857),
  modifiersGridGap: kioskScale(48.571),
  modifiersCardMinHeight: kioskScale(461.43),
  modifiersCardRadius: kioskScale(48.571),
  modifiersCardBorderWidth: kioskScale(6.071),
  modifiersCardPadding: kioskScale(54.642),
  modifiersCardImageSize: kioskScale(194.286),
  modifiersCardImageMarginBottom: kioskScale(36.429),
  modifiersCardNameSize: kioskScale(50),
  modifiersCardNameLineHeight: kioskScale(60.714),
  modifiersCardPriceSize: kioskScale(35),
  modifiersCardPriceLineHeight: kioskScale(48.571),
  modifiersCheckBadgeSize: kioskScale(72.857),
  modifiersCheckBadgeOffset: kioskScale(24.29),
  /** Check dentro del badge (~50% del diámetro, Figma 35:245). */
  modifiersCheckIconSize: kioskScale(38),
  modifiersBottomRadius: kioskScale(72.857),
  modifiersBottomPadding: kioskScale(48.571),
  modifiersBottomPaddingTop: kioskScale(51.607),
  modifiersBottomGap: kioskScale(36.429),
  modifiersBottomBorderWidth: kioskScale(3.036),
  modifiersChipsHeight: kioskScale(91.5),
  modifiersChipsGap: kioskScale(24.286),
  modifiersChipPaddingHorizontal: kioskScale(39.465),
  modifiersChipPaddingVertical: kioskScale(21.25),
  modifiersChipBorderWidth: kioskScale(3.036),
  modifiersChipFontSize: kioskScale(35),
  modifiersChipLineHeight: kioskScale(48.571),
  modifiersChipRemoveWidth: kioskScale(22.768),
  modifiersChipRemoveHeight: kioskScale(30.357),
  modifiersChipLabelMaxWidth: kioskScale(280),
  modifiersSummaryLabelSize: kioskScale(45),
  modifiersSummaryLabelLineHeight: kioskScale(60.714),
  modifiersSummaryPriceSize: kioskScale(55),
  modifiersSummaryPriceLineHeight: kioskScale(85),
  modifiersScrollBottomInset: kioskScale(560),
  /** Compact +/- on modifier cards (Figma 172:32). */
  modifierCardStepperGap: kioskScale(28),
  modifierCardStepperPaddingHorizontal: kioskScale(16),
  modifierCardStepperPaddingVertical: kioskScale(10),
  modifierCardStepperBorderWidth: kioskScale(2.88),
  modifierCardStepperButtonSize: kioskScale(56),
  modifierCardStepperValueSize: kioskScale(36),
  modifierCardStepperValueLineHeight: kioskScale(44),
  modifierCardStepperValueMinWidth: kioskScale(32),
  modifierCardStepperIconWidth: kioskScale(24),
  modifierCardStepperIconHeight: kioskScale(28),
  /** Unit pagination badge (Figma 178:2). */
  modifierUnitBadgeMarginTop: kioskScale(32),
  modifierUnitBadgePaddingHorizontal: kioskScale(24),
  modifierUnitBadgePaddingVertical: kioskScale(12),
  modifierUnitBadgeFontSize: kioskScale(28),
  modifierUnitBadgeLineHeight: kioskScale(36),
  modifierUnitBadgeRadius: kioskScale(999),

  /** P7 · Carrito (Figma node 35:316) */
  cartHeaderPaddingHorizontal: kioskScale(72.857),
  cartTitleSize: kioskScale(70),
  cartTitleLineHeight: kioskScale(91.071),
  cartSubtitleSize: kioskScale(42.5),
  cartSubtitleLineHeight: kioskScale(50),
  cartSectionGap: kioskScale(48.571),
  cartItemRadius: kioskScale(48.571),
  cartItemBorderWidth: kioskScale(3.036),
  cartItemPaddingVertical: kioskScale(20),
  cartItemPaddingRight: kioskScale(40),
  cartItemContentPaddingLeft: kioskScale(24),
  cartItemGap: kioskScale(32),
  cartItemImageSlotWidth: kioskScale(302),
  cartItemImageSlotPadding: kioskScale(20),
  cartItemImageHeight: kioskScale(220),
  cartItemNameSize: kioskScale(55),
  cartItemNameLineHeight: kioskScale(62),
  cartItemModifiersSize: kioskScale(30),
  cartItemModifiersLineHeight: kioskScale(36),
  cartItemPriceSize: kioskScale(55),
  cartItemPriceLineHeight: kioskScale(62),
  cartItemContentGap: kioskScale(8),
  cartItemTextGap: kioskScale(4),
  cartLineStepperGap: kioskScale(20),
  cartLineStepperPaddingHorizontal: kioskScale(16),
  cartLineStepperPaddingVertical: kioskScale(8),
  cartLineQtyButtonSize: kioskScale(72),
  cartLineQtyValueSize: kioskScale(50),
  cartLineQtyValueLineHeight: kioskScale(54),
  cartLineQtyIconWidth: kioskScale(26),
  cartLineQtyIconHeight: kioskScale(26),
  cartLineRemoveButtonSize: kioskScale(72),
  cartLineRemoveBorderWidth: kioskScale(5),
  cartAddMoreBorderWidth: kioskScale(6.071),
  cartAddMoreRadius: kioskScale(48.571),
  cartAddMorePaddingVertical: kioskScale(54.642),
  cartAddMoreIconWidth: kioskScale(42.5),
  cartAddMoreIconHeight: kioskScale(48.571),
  cartAddMoreLabelSize: kioskScale(50),
  cartAddMoreLabelLineHeight: kioskScale(72.857),
  cartScrollBottomInset: kioskScale(280),

  /** P8 · Resumen de pago en carrito (Figma 41:92) */
  cartCheckoutRadius: kioskScale(72.857),
  cartCheckoutPadding: kioskScale(48.571),
  cartCheckoutPaddingTop: kioskScale(51.607),
  cartCheckoutGap: kioskScale(36.429),
  cartCheckoutRowGap: kioskScale(20),
  cartCheckoutBorderWidth: kioskScale(3.036),
  cartCheckoutSummaryPaddingBottom: kioskScale(24.286),
  cartCheckoutDividerHeight: kioskScale(3.036),
  /** Figma 41:93 — banner tasa BCV */
  cartCheckoutBcvBannerRadius: kioskScale(46.08),
  cartCheckoutBcvBannerBorderWidth: kioskScale(2.88),
  cartCheckoutBcvBannerPaddingVertical: kioskScale(37.44),
  cartCheckoutBcvBannerPaddingHorizontal: kioskScale(48.96),
  cartCheckoutBcvLabelSize: kioskScale(35),
  cartCheckoutBcvLabelLineHeight: kioskScale(46.08),
  cartCheckoutBcvRateSize: kioskScale(40),
  cartCheckoutBcvRateLineHeight: kioskScale(57.6),
  /** Figma 41:100 — filas subtotal / IVA */
  cartCheckoutRowLabelSize: kioskScale(40),
  cartCheckoutRowLabelLineHeight: kioskScale(60.714),
  cartCheckoutRowValueSize: kioskScale(40),
  cartCheckoutRowValueLineHeight: kioskScale(60.714),
  /** Figma 41:112 — total */
  cartCheckoutTotalLabelSize: kioskScale(55),
  cartCheckoutTotalLabelLineHeight: kioskScale(85),
  cartCheckoutTotalValueSize: kioskScale(55),
  cartCheckoutTotalValueLineHeight: kioskScale(97.143),
  cartCheckoutScrollBottomInset: kioskScale(520),

  /** P9 · Método de pago */
  paymentMethodContentPaddingHorizontal: kioskScale(69.12),
  paymentMethodSectionGap: kioskScale(50),
  paymentMethodHeaderGap: kioskScale(20),
  paymentMethodListGap: kioskScale(50),
  paymentMethodCardRadius: kioskScale(69.12),
  paymentMethodCardPadding: kioskScale(60.48),
  paymentMethodCardGap: kioskScale(46.08),
  paymentMethodCardBorderWidth: kioskScale(2.88),
  paymentMethodIconSize: kioskScale(138.24),
  paymentMethodIconRadius: kioskScale(46.08),
  paymentMethodIconBorderWidth: kioskScale(2.88),
  paymentMethodTitleSize: kioskScale(51.84),
  paymentMethodTitleLineHeight: kioskScale(80.64),
  paymentMethodSubtitleSize: kioskScale(34.56),
  paymentMethodSubtitleLineHeight: kioskScale(46.08),
  paymentMethodRadioSize: kioskScale(69.12),
  paymentMethodRadioBorderWidth: kioskScale(5.76),
  paymentMethodRadioInnerSize: kioskScale(34.56),

  /** P10 (a) · POS / ECR */
  paymentPosContentPaddingHorizontal: kioskScale(69.12),
  paymentPosSectionGap: kioskScale(50),
  paymentPosHeroGap: kioskScale(20),
  paymentPosHeroMinHeight: kioskScale(380),
  paymentPosHeroIconOuterSize: kioskScale(180.084),
  paymentPosHeroIconRadius: kioskScale(60.028),
  paymentPosHeroIconBorderWidth: kioskScale(3.752),
  paymentPosHeroIconWidth: kioskScale(84.415),
  paymentPosHeroIconHeight: kioskScale(75.035),
  paymentPosTitleSize: kioskScale(70),
  paymentPosTitleLineHeight: kioskScale(91.071),
  paymentPosSubtitleSize: kioskScale(42.5),
  paymentPosSubtitleLineHeight: kioskScale(50),
  paymentPosActionsGap: kioskScale(100),
  paymentPosSyncIconSize: kioskScale(64),
  paymentPosSyncGap: kioskScale(15),

  /** P10 (b) · Pago móvil y QR (Figma 48:2) */
  paymentMobileHeroMinHeight: kioskScale(435),
  paymentMobileHeroIconHeight: kioskScale(96),
  paymentMobileDetailsMaxWidth: kioskScale(942),
  paymentMobileFieldsColumnWidth: kioskScale(445),
  paymentMobileFieldsGap: kioskScale(50),
  /** Espacio entre filas de cuenta destino / formulario pagador (pantalla pago móvil compacta). */
  paymentMobileFieldsGapCompact: kioskScale(22),
  paymentMobileLabelValueGap: kioskScale(6),
  paymentMobileReadOnlyMinHeightCompact: kioskScale(36),
  paymentMobileTransferBlockGap: kioskScale(18),
  paymentMobileFormFieldGap: kioskScale(6),
  paymentMobileScreenSectionGap: kioskScale(28),
  paymentMobileFieldWidth: kioskScale(345),
  paymentMobileFieldLabelSize: kioskScale(35),
  paymentMobileFieldLabelLineHeight: kioskScale(57.714),
  paymentMobileFieldLabelLineHeightCompact: kioskScale(42),
  paymentMobileFieldValueSize: kioskScale(45),
  paymentMobileFieldMinHeight: kioskScale(64),
  paymentMobileFieldRadius: kioskScale(34.629),
  paymentMobileQrSize: kioskScale(396.511),
  paymentMobileFieldTallMinHeight: kioskScale(84),
  /** P10 (c) · Confirmar pago móvil (Figma 205:176) */
  paymentMobileConfirmSectionGap: kioskScale(40),
  paymentMobileConfirmFieldsGap: kioskScale(30),
  paymentMobileConfirmFieldMinHeight: kioskScale(122),
  paymentMobileConfirmDocumentSize: kioskScale(42.5),
  paymentMobileConfirmDocumentLineHeight: kioskScale(50),
  /** Espacio entre Continuar y Cambiar cédula (Figma 205:345 usa 100; más compacto en kiosk). */
  paymentMobileConfirmActionsGap: kioskScale(30),
  /** P10 (d) · Nueva cédula pago móvil (Figma 205:390) */
  paymentMobileChangeDocumentSectionGap: kioskScale(50),
  paymentMobileChangeDocumentHeroMinHeight: kioskScale(490),
  paymentMobileChangeDocumentTypeWidth: kioskScale(178),

  /** P10 (c) · Zelle (Figma 48:66) */
  paymentZelleHeroMinHeight: kioskScale(392),
  paymentZelleHeroIconWidth: kioskScale(64.845),
  paymentZelleHeroIconHeight: kioskScale(106.632),
  paymentAccountFieldFullWidth: kioskScale(446),

  /** P11–P12.1 · Referencia (Figma 51:2 · 51:53 · 52:121) */
  paymentReferenceContentPaddingHorizontal: kioskScale(69.12),
  paymentReferenceSectionGap: kioskScale(50),
  paymentReferenceHeroMinHeight: kioskScale(380),
  paymentReferenceTitleSize: kioskScale(70),
  paymentReferenceTitleLineHeight: kioskScale(91.071),
  paymentReferenceSubtitleSize: kioskScale(42.5),
  paymentReferenceSubtitleLineHeight: kioskScale(50),
  paymentReferenceInputRadius: kioskScale(46.08),
  paymentReferenceInputBorderWidth: kioskScale(2.88),
  paymentReferenceInputPaddingHorizontal: kioskScale(48.96),
  paymentReferenceInputPaddingVertical: kioskScale(37.44),
  paymentReferenceInputLabelSize: kioskScale(40),
  /** P8.2 · Registro cliente (Figma 205:2) */
  customerBillingHeroIconSize: kioskScale(110),
  customerRegisterNameRowGap: kioskScale(35),
  customerRegisterFormFieldGap: kioskScale(30),
  /** Selector 0 + código (4 dígitos, Figma 205:36 ≈ 237px). */
  customerPhoneOperatorSelectorWidth: kioskScale(237),
  /** P20 · Localizador (Figma 180:187) */
  locatorHeroIconSize: kioskScale(204),
  locatorHeroGap: kioskScale(22.464),
  locatorFormActionsGap: kioskScale(50),
  paymentReferenceInputLabelLineHeight: kioskScale(46.08),
  paymentReferenceDigitsSize: kioskScale(48),
  paymentReferenceDigitsLetterSpacing: kioskScale(12),
  paymentReferenceHourglassWidth: kioskScale(139),
  paymentReferenceHourglassHeight: kioskScale(174),
  paymentReferenceStatusCenterGap: kioskScale(22.464),
  paymentReferenceDontCloseGap: kioskScale(15),
  paymentReferenceDontCloseIconSize: kioskScale(64),
  paymentReferenceErrorIconSize: kioskScale(206.5),
  paymentReferenceErrorActionsGap: kioskScale(30),
  paymentReferenceKeypadGap: kioskScale(20),
  paymentReferenceKeypadKeyHeight: kioskScale(100),
  paymentReferenceKeypadKeyRadius: kioskScale(24),
  paymentReferenceKeypadKeyFontSize: kioskScale(48),
  paymentReferenceMaxWidth: kioskScale(942),

  /** P14 / P14.1 · Resultado pedido (Figma 57:235 · 57:346) */
  paymentOutcomeContentGap: kioskScale(100),
  paymentOutcomeBlockGap: kioskScale(22.464),
  paymentOutcomeOrderCardWidth: kioskScale(868),
  paymentOutcomeOrderCardRadius: kioskScale(46.286),
  paymentOutcomeOrderCardBorderWidth: kioskScale(2.893),
  paymentOutcomeOrderCardPaddingHorizontal: kioskScale(49.179),
  paymentOutcomeOrderCardPaddingVertical: kioskScale(49.5),
  paymentOutcomeOrderCardInnerGap: kioskScale(10),
  paymentOutcomeOrderLabelSize: kioskScale(42.5),
  paymentOutcomeOrderLabelLineHeight: kioskScale(57.857),
  paymentOutcomeOrderNumberSize: kioskScale(100),
  paymentOutcomeOrderNumberLineHeight: kioskScale(138.857),
  paymentOutcomeHintIconSize: kioskScale(64),
  paymentOutcomeHintGap: kioskScale(15),
  paymentOutcomeHintTextSize: kioskScale(35),
  paymentOutcomeHintTextLineHeight: kioskScale(50),
  paymentOutcomeSubtitleSemiboldSize: kioskScale(42.5),

  /** P15 · Ticket QR (Figma 64:2) */
  paymentOutcomeQrTitleSize: kioskScale(70),
  paymentOutcomeQrTitleLineHeight: kioskScale(91.071),
  paymentOutcomeQrSubtitleSize: kioskScale(42.5),
  paymentOutcomeQrSubtitleLineHeight: kioskScale(50),
  paymentOutcomeQrBannerIconSize: kioskScale(61.463),
  paymentOutcomeQrBannerTextSize: kioskScale(40),
  paymentOutcomeQrBannerTextLineHeight: kioskScale(46.08),
  paymentOutcomeQrBannerInnerGap: kioskScale(23.04),
  paymentOutcomeQrSummaryRowGap: kioskScale(15),

  /** P19 · engineering (Figma 72:33) */
  paymentAssistanceIconSize: kioskScale(204),

  /** P17 · shopping_cart_off (Figma 66:85) */
  orderingOutOfStockIconSize: kioskScale(204),
} as const;

export const kioskScreenShadows = {
  card: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: kioskScale(2.286) },
    shadowOpacity: 0.25,
    shadowRadius: kioskScale(10),
    elevation: 4,
  },
  backButton: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: kioskScale(2.286) },
    shadowOpacity: 0.05,
    shadowRadius: kioskScale(4.571),
    elevation: 2,
  },
  /** P4 · Menú — lighter card elevation */
  menuCard: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: kioskScale(2.88) },
    shadowOpacity: 0.05,
    shadowRadius: kioskScale(2.88),
    elevation: 2,
  },
  cartBar: {
    shadowColor: '#1e293b',
    shadowOffset: { width: 0, height: kioskScale(23.04) },
    shadowOpacity: 0.3,
    shadowRadius: kioskScale(36),
    elevation: 12,
  },
  productImage: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: kioskScale(5.76) },
    shadowOpacity: 0.07,
    shadowRadius: kioskScale(8.64),
    elevation: 4,
  },
  /** P5 · Figma 35:164 — drop-shadow del panel crema */
  productDetailHeroPanel: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: kioskScale(2.88) },
    shadowOpacity: 0.05,
    shadowRadius: kioskScale(2.88),
    elevation: 2,
  },
  productDetailBottomBar: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: kioskScale(-28.8) },
    shadowOpacity: 0.05,
    shadowRadius: kioskScale(57.6),
    elevation: 12,
  },
  modifierCardImage: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: kioskScale(6.071) },
    shadowOpacity: 0.06,
    shadowRadius: kioskScale(6.071),
    elevation: 3,
  },
  modifiersBottomBar: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: kioskScale(-20) },
    shadowOpacity: 0.05,
    shadowRadius: kioskScale(20),
    elevation: 12,
  },
  /** P8 · Figma 41:92 */
  cartCheckoutSheet: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: kioskScale(-20) },
    shadowOpacity: 0.08,
    shadowRadius: kioskScale(28.8),
    elevation: 16,
  },
  paymentMethodCard: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: kioskScale(5) },
    shadowOpacity: 0.15,
    shadowRadius: kioskScale(5),
    elevation: 6,
  },
} as const;
